// stock-control-ui-react/src/modules/features/reports/components/stock-report/stock-report.jsx
import './stock-report.css'
import { useState } from "react";
import { fetchStockReport } from "../../services/stock-report-service";
import LoadingSpinner from "../../../../shared/components/loading-spinner/loading-spinner";
import ErrorBox from "../../../../shared/components/error-box/error-box";

export default function StockReport() {
    const [isLoading, setIsLoading] = useState(false);
    const [stockReportData, setStockReportData] = useState(null);
    const [error, setError] = useState(null);

    async function getStockReport() {
        try {
            setIsLoading(true);
            const stockData = await fetchStockReport();
            console.log(stockData)
            setStockReportData(stockData);
            setIsLoading(false);
        } catch (error) {
            console.error('Error fetching stock report:', error);
            setError(error);
            setIsLoading(false);
        }
    }

    return (
        <div className="component-container">
            <h2>Stock Report</h2>
            <div className="fields-container">
                <div>
                    <input type="date" className="form-control" placeholder="Movement Date" />
                </div>
                <div>
                    <input type="text" className="form-control" placeholder="Product Code" />
                </div>
                <div className="buttons-container">
                    <button type="button" className="btn btn-primary"
                        onClick={getStockReport}
                        disabled={isLoading}>Generate Report</button>
                </div>
            </div>
            {isLoading && <LoadingSpinner loadingText="Loading stock report..." />}
            {!isLoading && stockReportData?.length > 0 &&
                <div className="stock-report-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Product Code</th>
                                <th>Total Inbound</th>
                                <th>Total Outbound</th>
                                <th>Balance</th>
                            </tr>
                        </thead>
                        <tbody>
                            {stockReportData.map(product => (
                                <tr key={product.productCode}>
                                    <td>{product.productName}</td>
                                    <td>{product.productCode}</td>
                                    <td>{product.totalInbound}</td>
                                    <td>{product.totalOutbound}</td>
                                    <td>{product.balance}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            }
            {!isLoading && stockReportData && !stockReportData.length &&
                <div className="stock-report-container">
                    <p>No data available.</p>
                </div>
            }
            {error && <ErrorBox error={error} />}
        </div>
    );
}

// stock-control-ui-angular/src/modules/features/reports/components/stock-report/stock-report.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { StockReportService } from '../../services/stock-report.service';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { provideNativeDateAdapter } from '@angular/material/core';

@Component({
  selector: 'app-stock-report',
  providers: [provideNativeDateAdapter()],
  imports: [ 
    FormsModule, 
    CommonModule, 
    MatInputModule, 
    MatButtonModule, 
    MatDatepickerModule, 
    ReactiveFormsModule,
   ],
  templateUrl: './stock-report.component.html',
  styleUrl: './stock-report.component.scss'
})
export class StockReportComponent {

  readonly date = new FormControl(new Date());
  movementDate: Date = new Date();
  productCode: string = '';

  stockData: any[] = []; // Replace with actual data type

  constructor(private stockReportService: StockReportService) { }

  fetchStockData() {
    this.stockReportService.fetchStockReport(this.movementDate, this.productCode).subscribe(
      stockReportItems => {
        //TODO: Enhance messages presentation in the UI
        this.stockData = stockReportItems;
        console.log('Stock report fetched successfully!', stockReportItems.length);

        if(!stockReportItems?.length) {
          alert('No stock report found for the given date!');
        }
      },
      error =>
      {
        if(error.error?.detail) {
          alert(error.error?.detail);
        } else {
          alert('Error fetching stock report!');
        }
        console.error('Error fetching stock report:', error);
      }
    );
  }

  generateReport() {
    if(this.date?.value) {
      this.movementDate = this.date.value;
    }

    if(!this.movementDate) {
      alert('Please inform a Movement Date!');
      return;
    }

    this.fetchStockData();
  }

}
<div class="form-group align-center">
    <h2>Stock Report</h2>
    
    <div>
        <mat-form-field>
            <mat-label>Movement Date</mat-label>
            <input matInput [matDatepicker]="picker" [formControl]="date">
            <mat-hint>MM/DD/YYYY</mat-hint>
            <mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
            <mat-datepicker #picker></mat-datepicker>
        </mat-form-field>
    </div>
    
    <div>
        <mat-form-field>
            <mat-label>Product Code</mat-label>
            <input matInput type="text" id="productCode" name="productCode" placeholder="Enter code" [(ngModel)]="productCode">
        </mat-form-field>
    </div>
    
    <div class="button-group">
        <button mat-raised-button class="btn btn-primary" (click)="generateReport()">Generate Report</button>
    </div>
    
    <div *ngIf="stockData?.length">
        <table *ngIf="stockData?.length">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Product Code</th>
                    <th>Total Inbound</th>
                    <th>Total Outbound</th>
                    <th>Balance</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let item of stockData">
                    <td>{{ item.productName }}</td>
                    <td>{{ item.productCode }}</td>
                    <td>{{ item.totalInbound }}</td>
                    <td>{{ item.totalOutbound }}</td>
                    <td>{{ item.balance }}</td>
                </tr>
            </tbody>
        </table>
        <div *ngIf="!stockData?.length" class="alert alert-info">
            <p>No data available.</p>
        </div>
    </div>
</div>
