// stock-control-ui-react/src/modules/features/product-movement/components/add-product-movement/add-product-movement.jsx
import { useState } from "react";
import ProductMovementModel from "../../models/product-movement-model";
import { postProductMovement } from "../../services/product-movement-service";

export default function AddProductMovement() {

    const [productCode, setProductCode] = useState("PROD123");
    const [movementType, setMovementType] = useState("0");
    const [quantity, setQuantity] = useState(25);
    const [isPosting, setIsPosting] = useState(false);
    const [error, setError] = useState(null);

    const handleAddMovement = async () => {
        setIsPosting(true);
        setError(null);
        const productMovement = new ProductMovementModel(productCode, movementType, quantity);

        try {
            const productMovementId = await postProductMovement(productMovement);
            console.log("Posted product movement with ID:", productMovementId);
        } catch (error) {
            console.error("Error posting product movement:", error);
            setError(error);
        } finally {
            setIsPosting(false);
        }
    };

    return (
        <div className="component-container">
            <h2>Add Product Movement</h2>

            <div className="fields-container">
                <div>
                    <input type="text" class="form-control" placeholder="Product Code" />
                </div>
                <div>
                    <select class="form-control" id="movementType">
                        <option value="">Select Movement Type</option>
                        <option value="0">Inbound</option>
                        <option value="1">Outbound</option>
                    </select>
                </div>
                <div>
                    <input type="number" class="form-control" placeholder="Quantity" />
                </div>
            </div>
            <div className="buttons-container">
                <button type="button" className="btn btn-primary"
                    onClick={handleAddMovement}
                    disabled={isPosting}>Add Movement</button>
            </div>

            {isPosting && <div>Sending product movement...</div>}
            {error && <div>Error: {error.message}</div>}
            {/* TODO: Create a component to display errors! */}

        </div>
    );
}

// stock-control-ui/src/modules/features/product-movement/components/add-product-movement/add-product-movement.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ProductMovementService } from '../../services/product-movement.service';
import { ProductMovementModel } from '../../models/product-movement-model';
import { MatInputModule } from '@angular/material/input';

@Component({
  selector: 'app-add-product-movement',
  templateUrl: './add-product-movement.component.html',
  styleUrl: './add-product-movement.component.scss',
  imports: [ FormsModule, MatInputModule ],
})
export class AddProductMovementComponent {

  productMovement: ProductMovementModel = new ProductMovementModel('', 0, 0);

  constructor(private productMovementService: ProductMovementService) { }

  addProductMovement() {
    console.log('Product Movement:', this.productMovement);
    this.productMovementService.postProductMovement(this.productMovement).subscribe(
      productMovementId => {
        //TODO: Enhance messages presentation in the UI
        alert('Product movement added successfully!');
        console.log('Product movement added successfully!', productMovementId);
        this.productMovement = new ProductMovementModel('', 0, 0);
      },
      error =>
      {
        if(error.error?.detail) {
          alert(error.error?.detail);
        } else {
          alert('Error adding product movement!');
        }
        console.error('Error adding product movement:', error);
      }
    );
  }

}
<div class="form-group align-center">
    <h2>Add Product Movement</h2>

    <form>
        <div>
            <mat-form-field>
                <mat-label>Product Code</mat-label>
                <input matInput type="text" id="productCode" name="productCode" placeholder="Enter code" [(ngModel)]="productMovement.productCode">
            </mat-form-field>
        </div>

        <div>
            <label for="productMovementType">Movement Type</label>
            <select id="productMovementType" name="productMovementType" class="form-control" [(ngModel)]="productMovement.movementType">
                <option value="" disabled selected>Select an option</option>
                <option value="0">Inbound</option>
                <option value="1">Outbound</option>
            </select>
        </div>

        <div>
            <mat-form-field>
                <mat-label>Quantity</mat-label>
                <input matInput type="text" id="productQuantity" name="productQuantity" class="form-control" placeholder="Enter quantity" [(ngModel)]="productMovement.quantity">
            </mat-form-field>
        </div>

        <div>
            <button mat-raised-button color="primary" (click)="addProductMovement()">Add Movement</button>
        </div>
    </form>

</div>
